<?php /**
 * @file
 * Contains \Drupal\timefield\Plugin\Field\FieldFormatter\TimeFieldDefaultFormatter.
 */

namespace Drupal\timefield\Plugin\Field\FieldFormatter;

use Drupal\Core\Field\FormatterBase;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * @FieldFormatter(
 *  id = "timefield_default_formatter",
 *  label = @Translation("Timefield formatter"),
 *  field_types = {"timefield"}
 * )
 */
class TimeFieldDefaultFormatter extends FormatterBase {

  /**
   * {@inheritdoc}
   */
  public static function defaultSettings() {

    return array(
      'display_format' => array(
        'hour' => 'g',
      ),
    ) + parent::defaultSettings();
  }


  public function settingsForm(array $form, FormStateInterface $form_state) {
    $element = parent::settingsForm($form, $form_state); // TODO: Change the autogenerated stub
    $settings = $this->getSettings();
    $element += _timefield_display_format_form('display_format', "Individual Time Display Settings", $settings);
    return $element;
  }

  /**
   * {@inheritdoc}
   */
  public function viewElements(FieldItemListInterface $items, $langcode) {
    $settings = $this->getSettings();
    $field_settings = $this->getFieldSettings();
    $element = array();
    foreach ($items as $delta => $item) {
      if (!empty($item->value)) {
        $element[$delta]['#markup'] = trim(timefield_integer_to_time($settings['display_format'], $item->value));
      }
    }


    return $element;
  }
}
